version: "3.9"

networks:
  wordpress:

services:
  server:
    build:
      context: .
      dockerfile: ./server/Dockerfile
    container_name: "${APP_NAME}-server"
    ports:
      - "${APP_PORT}:80"
    working_dir: /var/www/
    environment:
      - "DATABASE_URL=mysql://${MYSQL_USER}:${MYSQL_PASS}@db_server:3306/${MYSQL_DB}?serverVersion=10.5"
    volumes:
      - ./www:/var/www/
      - ./server/wp-config.php:/var/www/wp-config.php
      - ./server/apache/sites-enabled:/etc/apache2/sites-enabled
      - ./server/apache/apache2.conf:/etc/apache2/apache2.conf
      - ./server/php/php.ini:/usr/local/etc/php/conf.d/extra-php-config.ini
      - ./server/logs/error.log:/var/log/apache2/error.log
    depends_on:
      - db_server
    networks:
      - wordpress

  db_server:
    image: mariadb
    container_name: "${APP_NAME}-db"
    restart: always
    ports:
      - "${DB_PORT}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASS}"
      MYSQL_USER: "${MYSQL_USER}"
      MYSQL_PASSWORD: "${MYSQL_PASS}"
      MYSQL_DATABASE: "${MYSQL_DB}"
    volumes:
      - db_data:/var/lib/mysql
      - ./server/db/conf/my.cnf:/etc/mysql/conf.d/my.cnf
    networks:
      - wordpress

  db_admin:
    image: phpmyadmin
    container_name: "${APP_NAME}-db-admin"
    ports:
      - "${APP_DB_ADMIN_PORT}:80"
    environment:
      PMA_HOST: db_server
    depends_on:
      - db_server
    volumes:
      - db_admin_data:/var/www
    networks:
      - wordpress

volumes:
  db_data:
  db_admin_data:
